from __future__ import annotations

from .models import Signal
from .scanner_engine import SignalEngine


def build_test_signals() -> list[Signal]:
    return [
        Signal(
            exchange="Bybit",
            symbol="BTCUSDT",
            signal_type="pump",
            oi_period_minutes=15,
            oi_change_percent=8.42,
            oi_change_value=12500.0,
            oi_change_usd=1_520_000.0,
            oi_direction="up",
            signals_today=1,
            price_change_percent=3.15,
            price_change_value=2100.0,
            price_direction="up",
            volume_change_percent=12.5,
            trade_count=15420,
            spread=0.1,
            funding_rate=0.0001,
            liquidation_estimate=None,
            vwap=None,
            atr=None,
            rsi=58.2,
            ema_short=None,
            ema_long=None,
            volume_24h=5_000_000.0,
            volume_speed=None,
            signal_score=2,
            side="long",
            current_price=67500.0,
            current_open_interest=500_000.0,
            link=SignalEngine._coinglass_url("BTCUSDT", "Bybit"),
            details={"test": True},
        ),
        Signal(
            exchange="Binance",
            symbol="ETHUSDT",
            signal_type="dump",
            oi_period_minutes=15,
            oi_change_percent=-6.33,
            oi_change_value=-8200.0,
            oi_change_usd=-890_000.0,
            oi_direction="down",
            signals_today=1,
            price_change_percent=-2.87,
            price_change_value=-85.0,
            price_direction="down",
            volume_change_percent=8.1,
            trade_count=22100,
            spread=0.02,
            funding_rate=-0.0002,
            liquidation_estimate=None,
            vwap=None,
            atr=None,
            rsi=42.0,
            ema_short=None,
            ema_long=None,
            volume_24h=3_200_000.0,
            volume_speed=None,
            signal_score=2,
            side="short",
            current_price=2950.0,
            current_open_interest=280_000.0,
            link=SignalEngine._coinglass_url("ETHUSDT", "Binance"),
            details={"test": True},
        ),
    ]
